<a href="https://colab.research.google.com/github/YugyeongJo/SeSAC_Python_Study/blob/main/docs/02_Python_Basic(Operator)_0702.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python 기초

<목차>
1. 변수
2. 연산자
3. 제어문
4. 함수
5. 자료형 1
6. 자료형 2
7. 정규표현식
8. 판다스
9. 시각화
10. 파일 입출력

<hr>

# 2. 연산자(문법)

## 연산자
- 연산을 수행하는 기호

|Operators|Type|비고|
|--|--|--|
|+, -, *, /, %|Arithmetic operator|산술연산자|
|=, +=, ==, *=, %=|Assignment operator|대입(복합)연산자|
|AND, OR, NOT|Logical operator|논리연산자|
|<, <=, >, >=, !=|Relational operator|비교연산자|
|&, ,\|, <<, >>, -. ^|Bitwise operator|비트연산자|

### 산술연산자(Arithmetic operator)

- 덧셈(+), 뺄셈(-), 곱셈(*), 나눗셈(/)은 수학에서의 연산과 동일
- 나머지 연산자(%)는 피젯수를 젯구로 나눈 나머지 값을 구하는 연산
- //는 몫을 계산하며, **는 제곱(승수)를 계산하는 연산자

|Operators|Explanation|비고|
|--|--|--|
|+|덧셈|문자열 더하기도 가능|
|-|뺄셈||
|*|곱셈||
|/|나눗셈||
|//|몫||
|%|나머지||
|**|제곱||

In [ ]:
# 변수 입력
a = 10
b = 3

In [ ]:
# 덧셈
sum_result = a + b
print(f"a + b = {sum_result}")

a + b = 13


In [ ]:
# 뺄셈
sub_result = a - b
print(f"a - b = {sub_result}")

a - b = 7


In [ ]:
# 곱셈
mul_result = a * b
print(f"a * b = {mul_result}")

a * b = 30


In [ ]:
# 나눗셈
div_result = a / b
print(f"a / b = {div_result}")

a / b = 3.3333333333333335


In [ ]:
# 나머지
mod_result = a % b
print(f"a % b = {mod_result}")

a % b = 1


In [ ]:
# 나머지
pow_result = a ** b
print(f"a / b = {pow_result}")

a / b = 1000


In [ ]:
import numpy as np

data = np.array([10,20,30,40,50])
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print(f"정규화된 데이터 : {normalized_data}")
# 계산 과정:
# [0, 10, 20, 30, 40] / (50 - 10)
# [0, 10, 20, 30, 40] / 40
# [0, 0.25, 0.5, 0.75, 1.0]

# 정규화 : 데이터의 스케일을 동일하게 맞춤으로써 특정 특징이 다른 특징보다 모델에 더 큰 영향을 미치는 것을 방지하기 위해 적용
# Min-Max Normalization
# Min-Max : 주어진 데이터를 최소값과 최대값 사이의 특정 범위로 변환. 일반적으로 0과 1 사이로 스케일링

정규화된 데이터 : [0.   0.25 0.5  0.75 1.  ]


In [ ]:
import numpy as np
y_true = np.array([1, 2, 3, 4, 5])
y_pred = np.array([1.1, 2.1, 2.9, 4.0, 5.1])

mse = np.mean((y_true - y_pred) ** 2)
print(f"평균 제곱 오차 (MSE): {mse}")

평균 제곱 오차 (MSE): 0.007999999999999997


In [ ]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])
standardized_data = (data - np.mean(data)) / np.std(data)
print(f"표준화된 데이터 : {standardized_data}")

표준화된 데이터 : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### 대입(복합)연산자 (Assignment operator)

- 대입연산자(=)은 변수에 값을 저장하기 위한 연산자, 할당연산자라고 부르기도 함
- =의 오른쪽은 값, 계산되어서 값으로 출력될 수 있는 표현식, 함수 호출 구문이 올 수 있음
- 복합대입연산자(=, +=, -=, *=, **=, /=, //=, %= 등)은 연산자와 대입연산자를 함께 사용

|Operators|Explanation|비고|
|--|--|--|
|=|할당||
|+=|더해서 할당||
|-=|빼서 할당||
|*=|곱해서 할당||
|**=|제곱해서 할당|
|/=|나눠서 할당||
|//=|몫을 할당||
|%=|나머지를 할당||

In [ ]:
# +=(더하기 할당)
x = 10
x += 5
print(f"덧셈 복합 연산 결과: {x}")

덧셈 복합 연산 결과: 15


In [ ]:
# -=(빼기 할당)
x = 20
x -= 7
print(f"빼기 복합 연산 결과: {x}")

빼기 복합 연산 결과: 13


In [ ]:
# *=(곱하기 할당)
x = 3
x *= 4
print(f"곱하기 복합 연산 결과: {x}")

곱하기 복합 연산 결과: 12


In [ ]:
# /=(나누기 할당)
x = 25
x /= 5
print(f"나누기 복합 연산 결과: {x}")

나누기 복합 연산 결과: 5.0


In [ ]:
weights = np.array([0.1, 0.2, 0.3])
learning_rate = 0.01
gradient = np.array([0.02, -0.03, 0.01])

# 가중치 업데이트
weights -= learning_rate * gradient
print(f"업데이트된 가중치 : {weights}")

업데이트된 가중치 : [0.0998 0.2003 0.2999]


In [ ]:
import numpy as np

data = np.array([10, 20, 30, 40, 50], dtype=float)
data -= np.min(data)
data /= np.max(data)
print(f"정규화된 데이터: {data}")

정규화된 데이터: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
losses = [0.5, 0.3, 0.2, 0.4]
total_loss = 0

for loss in losses:
  total_loss += loss

average_loss = total_loss / len(losses)
print(f"평균 손실 : {average_loss}")

평균 손실 : 0.35


In [ ]:
learning_rate = 0.1
decay_rate = 0.01

# 에포크마다 학습률 감소
for epoch in range(10):
  learning_rate -= decay_rate
  print(f"Epoch {epoch+1}, Learning Rate: {learning_rate}")

Epoch 1, Learning Rate: 0.09000000000000001
Epoch 2, Learning Rate: 0.08000000000000002
Epoch 3, Learning Rate: 0.07000000000000002
Epoch 4, Learning Rate: 0.06000000000000002
Epoch 5, Learning Rate: 0.05000000000000002
Epoch 6, Learning Rate: 0.040000000000000015
Epoch 7, Learning Rate: 0.030000000000000013
Epoch 8, Learning Rate: 0.02000000000000001
Epoch 9, Learning Rate: 0.01000000000000001
Epoch 10, Learning Rate: 1.0408340855860843e-17


In [ ]:
import numpy as np

data = np.array([1,2,3,4,5], dtype=float)
mean = np.mean(data)
std = np.std(data)

# 데이터 정규화
data -= mean
data /= std
print(f"정규화된 데이터 : {data}")

# Z-점수 정규화 (Z-score Normalization) 또는 **표준화 (Standardization)**
# 데이터의 평균을 0으로, 표준편차를 1로 맞추는 정규화 방식
# 평균을 기준으로 얼마나 떨어져 있는지를 확인
# SVM, 로지스틱 회귀, 신경망 등 여러 머신러닝 알고리즘에서 자주 사용

정규화된 데이터 : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
import numpy as np

# 가상의 이미지 데이터
image = np.array([[1, 2], [3, 4]])

# 이미지 밝기 증가
brightness_increase = 10
image += brightness_increase
print(f"밝기 증가한 이미지 : \n {image}")

밝기 증가한 이미지 : 
 [[11 12]
 [13 14]]


### 논리연산자 (Logical operator)

- True와 False의 논리값을 연산하여 연산값을 산출하는 연산자
- &와 AND 연산자는 양쪽 항의 값이 모두 True인 경우에만 True를 반환
- |와 OR 연산자는 양쪽 항 중에서 어느 한쪽만 True이면 True를 반환

|Operators|Explanation|비고|
|--|--|--|
|&|AND|논리곱|
|\||OR|논리합|
|and|AND|False로 판별되는 첫 번째 항의 결과를 반환|
|or|OR|True로 판별되는 첫 번째 항의 결과를 반환|
|not|NOT|논리반전|


In [ ]:
a = True
b = False

result = a and b
print(f"and 연산 결과 : {result}")

and 연산 결과 : False


In [ ]:
a = True
b = False

result = a or b
print(f"or 연산 결과 : {result}")

or 연산 결과 : True


In [ ]:
accuracy = 0.85
precision = 0.8

# 정확도가 0.8 이상이고, 정밀도가 0.75 이상일 때 모델 배포
def model_deployment_status(accuracy, precision):
  if accuracy >= 0.8 and precision >= 0.75:
    model_deployment = "Yes"
  else:
    model_deployment = "No"
  return print(f"모델 배포 여부는 {model_deployment}")

model_deployment_status(accuracy, precision)

모델 배포 여부는 Yes


In [ ]:
import numpy as np

# 가상의 데이터 생성
features = np.array([
    [0.1, 0.2, 0.3]
    , [0.4, 0.5, 0.6]
    , [0.7, 0.8, 0.9]
])

# 조건 : 첫 번째 특성이 0.3 이상인 행 선택
selected_features = features[features[:, 0] >= 0.3]
print("선택된 특성:\n", selected_features)

선택된 특성:
 [[0.4 0.5 0.6]
 [0.7 0.8 0.9]]


In [ ]:
import numpy as np

# 가상의 예측 결과 (확률 값)
predictions = np.array([
    [0.1, 0.7, 0.2]
    , [0.3, 0.4, 0.3]
    , [0.2, 0.2, 0.6]
])

# 클래스 1에 대한 예측
class_1_predictions = predictions[:,1] > 0.5
print(f"클래스 1 예측 결과 : {class_1_predictions}")

클래스 1 예측 결과 : [ True False False]


### 비교연산자 (Relational operator)

- 양 변의 값을 비교하는 연산자
- 크기를 비교해 결과를 True 또는 False로 반환
- 문자열 타입도 가능. 소문자가 대문자보다 큰 값으로 인식
- 논리 타입도 크기 비교가 가능. True가 False보다 큰 값으로 인식

|Operators|Explanation|비고|
|--|--|--|
|<|작다||
|<=|작거나 같다||
|>|크다||
|>=|크거나 같다||
|==|같으면 True|조건문에서 유용|
|!=|같지 않다||

In [ ]:
a = 10
b = 20

result = (a == b)
print(f"== 연산 결과 : {result}")

== 연산 결과 : False


In [ ]:
a = 10
b = 20

result = (a < b)
print(f"< 연산 결과 : {result}")

< 연산 결과 : True


In [ ]:
a = 10
b = 10

result = (a >= b)
print(f">= 연산 결과 : {result}")

>= 연산 결과 : True


In [ ]:
accuracy_model_1 = 0.85
accuracy_model_2 = 0.90

better_model = "Model 1" if accuracy_model_1 > accuracy_model_2 else "Model 2"
print(f"더 나은 모델 : {better_model}")

더 나은 모델 : Model 2


In [ ]:
import numpy as np

predictions = np.array([1, 0, 1, 1, 0])
actuals = np.array([1, 0, 1, 0, 0])

accuracy = np.mean(predictions == actuals)
print(f"정확도 : {accuracy}")

정확도 : 0.8


In [ ]:
learning_rate = 0.01
batch_size = 32

# 학습률과 배치 크기 조건을 비교
if learning_rate < 0.1 and batch_size >= 32:
  print("적절한 하이퍼파라미터 설정입니다.")
else:
  print("하이퍼파라미터를 조정해야 합니다.")

적절한 하이퍼파라미터 설정입니다.


## Bitwise operator 비트 연산자

- 숫자를 2진수로 변환하여 계산하는 연산자

|Operators|Explanation|비고|
|--|--|--|
|a & b|두 비트가 모두 1이면 1|AND 연산|
|a \| b|두 비트 중 하나 이상 1이면 1|OR 연산|
|a ^ b|두 비트가 같으면 0, 다르면 1|XOR 연산|
|~a|0을 1로, 1을 0으로 변환|NOT 연산|
|a >> n|a를 n비트만큼 오른쪽으로 이동, 2로 나눈 결과와 같음|Shift 연산|
|a << n|a를 n비트만큼 왼쪽으로 이동, 2를 곱한 결과와 같음|Shift 연산|

In [ ]:
x = 0b00101011
y = 0b00001111
print("{:08b}".format(x & y))

00001011


In [ ]:
x = 0b00101011
y = 0b00001111
print("{:08b}".format(x | y))

00101111


In [ ]:
x = 0b00101011
print("{:08b}".format(x >> 3))

00000101


In [ ]:
import numpy as np
x = 0b00101011
print("{:08b}, {:08b}m {:08b}".format(x, ~x, np.ubyte(~x)))

00101011, -0101100m 11010100


<ipython-input-32-cb9bc0648473>:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -44 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  print("{:08b}, {:08b}m {:08b}".format(x, ~x, np.ubyte(~x)))


## 포맷팅 format

- 문자, 숫자, 날짜 데이터에 형식을 지정하는 것
- 변수와 텍스트를 결합해서 보기 좋은 형식의 새로운 텍스트를 만들 때 사용

```
format() 메소드

print("텍스트 {변수1}, {변수2}".format(변수1, 변수2)
```

- 키워드 인자 사용
  변수명을 직접 지정하여 사용할 수 있음
  ```
  print("텍스트 {변수1}, {변수2}".format(변수1, 변수2)
  ```

- 딕셔너리 사용
  딕셔너리로부터 직접 값을 추출하여 사용할 수 있음
  ** 언패킹(딕셔너리를 풀어서 넣어줌)
  ```
  print("텍스트 {딕셔너리 키값}, {딕셔너리 값}".format(**딕셔너리 변수)
  ```

- 소수점 조절
  소수점 아래 자릿수를 정확하게 지정할 수 있음
  ```
  print("텍스트 {:.2f}".format(변수)
  ```

### 포매팅 : 패딩과 정렬

- 문자열의 정렬과 공백을 조절 가능

|Formating|Explanation|비고|
|--|--|--|
|{:<10}|문자열을 왼쪽 정렬하고, 전체 너비를 10칸으로 설정||
|{:^10}|문자열을 가운데 정렬하고, 전체 너비를 10칸으로 설정||
|{:>10}|문자열을 오른쪽 정렬하고, 전체 너비를 10칸으로 설정||
|{:.2f}|소수점 이하 2자리까지 표시||
|{:,}|천 단위마다 콤마를 넣어 표시||

In [ ]:
# 왼쪽 정렬
print("{:<10}".format("Alice"))

Alice     


In [ ]:
# 가운데 정렬
print("{:^10}".format("Alice"))

  Alice   


In [ ]:
# 오른쪾 정렬
print("{:>10}".format("Alice"))

     Alice


### 포매팅 : 날짜 포맷팅

- datetime 객체를 포맷팅할 때 사용

In [ ]:
from datetime import datetime
now = datetime.now()
print("The current time is {:%Y-%m-%d %H:%M}.".format(now))

The current time is 2024-07-02 14:45.


### 포매팅 : 문자 표현 및 위치 지정

- 중괄호 문자 표현
  중괄호를 문자로 표시하려면 이중 중괄호를 사용
- 위치 지정
  위치를 지정하고자 할때에는 인덱스를 사용하여 변수의 위치 지정


In [ ]:
# 중괄호 문자 표현
print("To display curly braces, use {{and }}.".format())

To display curly braces, use {and }.


In [ ]:
# 위치 인자 사용
name = "Luten"
age = 34

print("My name is {0} and I am {1} years old. Nice to meet you, {0}.".format(name, age))

My name is Luten and I am 34 years old. Nice to meet you, Luten.


### 포매팅 : % 연산자를 사용한 문자열 포맷팅

- Python의 오래된 방식. but, 여전히 사용

#### 주요 포맷 지정자

|Format|Explanation|
|--|--|
|%s|문자열|
|%d|정수|
|%f|부동소수점수|
|%x|16진수|
|%.2f|소수점 둘째 자리까니의 부동소수점 수|

In [ ]:
name = "Alice"
age = 30

print("My name is %s and I'm %d years old."% (name, age))

My name is Alice and I'm 30 years old.


In [ ]:
# 딕셔너리 사용
data = {"name": "Bob", "age":25}
print("%(name)s is %(age)d years old."% data)

Bob is 25 years old.


In [ ]:
# 너비 지정
print("%10s"%"test") # 10칸 너비의 우측 정렬
print("%-10s"%"test") # 10칸 너비의 좌측 정렬

      test
test      


In [ ]:
# 숫자 형식
print("%05d"% 42) # 5자리 정수, 앞을 0으로 채움
print("%.2f" % 3.14159) # 소수점 둘째 자리까지

00042
3.14


### 포매팅 : f-string

- f-strings은 문자열에 형식을 지정할 때 서식을 쉽게 만들 수 있도록 함
- 3.6 버전부터 사용할 수 있음
- 형식을 지정하는 문자열 앞에 f(또는 F)를 붙여주고 {} 안에 변수, 리터럴, 표현식 등을 직접 삽입하여 동적인 문자열을 생성

```
기본 사용법
변수의 값을 문자열 내에 직접 삽입할 수 있음

print(f"텍스트 {변수}")
```


In [ ]:
# 수식 사용 : f-string 내에서 직접 수식을 사용
a = 5
b = 10
print(f"{a}와 {b}의 합은 {a+b}입니다.")

5와 10의 합은 15입니다.


In [ ]:
# 함수 호출 : 함수 호출 결과를 바로 삽입
def greet(name):
  return f"안녕하세요, {name}님!"

print(f"인사 : {greet('카일')}")

인사 : 안녕하세요, 카일님!


In [ ]:
# 소수점 조절 : 소수점 이하 자릿수를 조절

pi = 3.141592
print(f"파이의 값은 {pi:.2f}입니다.")

파이의 값은 3.14입니다.


In [ ]:
number = 3.141592
formatted_string = f"원주율: {number:.2f}"
print(formatted_string)

원주율: 3.14


In [ ]:
name = "Alice"
age = 30
formatted_string = f"이름 : {name}, 나이 : {age}"
print(formatted_string)

이름 : Alice, 나이 : 30


In [ ]:
width = 5
height = 10
area = width * height
formatted_string = f"가로 : {width}, 세로 : {height}, 면적 : {area}"
print(formatted_string)

가로 : 5, 세로 : 10, 면적 : 50


In [ ]:
epoch = 10
loss = 0.25
accuracy = 0.92
formatted_string = f"Epoch: {epoch}, Loss: {loss:.4f}, Accuracy: {accuracy:.2%}"
print(formatted_string)

Epoch: 10, Loss: 0.2500, Accuracy: 92.00%


In [ ]:
learning_rate = 0.01
batch_size = 32
formatted_string = f"Learning Rate: {learning_rate}, Batch Size: {batch_size}"
print(formatted_string)

Learning Rate: 0.01, Batch Size: 32


In [ ]:
#  날짜와 시간 포맷팅 : datetime 객체를 포맷팅할 때 유용하게 사용
from datetime import datetime
import pytz

# UTC 기준의 현재 시간
utc_now = datetime.now(pytz.utc)
print(f"현재 UTC 시간은 {utc_now:%Y-%m-%d %H:%M}입니다.")

# 한국 표준시(KST)로 변환
kst = pytz.timezone('Asia/Seoul')
kst_now = utc_now.astimezone(kst)
print(f"현재 한국 시간은 {kst_now:%Y-%m-%d %H:%M}입니다.")


현재 UTC 시간은 2024-07-02 06:12입니다.
현재 한국 시간은 2024-07-02 15:12입니다.


In [ ]:
# 딕셔너리 항목 접근 : f-string을 사용하여 딕셔너리 항목에 접근 가능
person = {'name':'심 슨', 'age': 14}
print(f"{person['name']}의 나이는 {person['age']}살 입니다.")

심 슨의 나이는 14살 입니다.


In [ ]:
# 중괄호 문자 표현 : f-string에서 중괄호를 문자로 표시하려면 이중 중괄호를 사용
print(f"중괄호를 표시하려면 {{와 }}을 사용하세요.")

중괄호를 표시하려면 {와 }을 사용하세요.


<hr>

# 2. 연산자(문제)

## 문제1) 두 숫자를 입력받아 덧셈/뺄셈/곱셈/나눗셈 연산을 수행하여 결과를 출력하세요.

In [ ]:
num1 = float(input("첫번째 숫자 입력"))
num2 = float(input("두번째 숫자 입력"))

def calculator(num1, num2):
  Add = num1 + num2
  Subtract = num1 - num2
  Multiply = num1 * num2
  Divide = num1 / num2

  return print(f"첫번째 숫자: {num1}, 두번째 숫자 {num2} \n 덧셈:{Add}, 뺄셈:{Subtract}, 곱셈:{Multiply}, 나누셈:{Divide}")

calculator(num1, num2)

첫번째 숫자 입력10
두번째 숫자 입력5
첫번째 숫자: 10.0, 두번째 숫자 5.0 
 덧셈:15.0, 뺄셈:5.0, 곱셈:50.0, 나누셈:2.0


## 문제2) 두 숫자를 입력받아 나머지/제곱 연산을 수행하여 결과를 출력하세요.

In [ ]:
num1 = float(input("첫번째 숫자 입력"))
num2 = float(input("두번째 숫자 입력"))

def calculator(num1, num2):
  result1 = num1 % num2
  result2_num1 = num1**2
  result2_num2 = num2**2

  return print(f"첫번째 숫자: {num1}, 두번째 숫자 {num2} \n 나머지:{result1}, 첫번째수 제곱:{result2_num1}, 두번째수 제곱:{result2_num2}")

calculator(num1, num2)

첫번째 숫자 입력10
두번째 숫자 입력5
첫번째 숫자: 10.0, 두번째 숫자 5.0 
 나머지:0.0, 첫번째수 제곱:100.0, 두번째수 제곱:25.0


## 문제3) 주어진 숫자의 제곱근을 계산하여 출력하세요.

In [ ]:
# 숫자 변수 지정
num = 16

In [ ]:
# 거듭제곱 연산자 사용
num = 16
sqrt_num = num ** 0.5
print(f"{num}의 제곱근은 {sqrt_num}입니다.")

16의 제곱근은 4.0입니다.


In [ ]:
# math 모듈 사용
import math

sqrt_num = math.sqrt(num)
print(f"{num}의 제곱근은 {sqrt_num}입니다.")

16의 제곱근은 4.0입니다.


In [ ]:
# cmath 모듈 사용
import cmath

sqrt_num = cmath.sqrt(num)
print(f"{num}의 제곱근은 {sqrt_num}입니다.")

16의 제곱근은 (4+0j)입니다.


In [ ]:
# numpy 모듈 사용
import numpy as np

sqrt_num = np.sqrt(num)
print(f"{num}의 제곱근은 {sqrt_num}입니다.")

16의 제곱근은 4.0입니다.


In [ ]:
# sympy 모듈 사용
import sympy as sp

sqrt_num = sp.sqrt(num)
print(f"{num}의 제곱근은 {sqrt_num}입니다.")


16의 제곱근은 4입니다.


In [ ]:
# scipy 모듈 사용
from scipy import sqrt

sqrt_num = sqrt(num)
print(f"{num}의 제곱근은 {sqrt_num}입니다.")

16의 제곱근은 4.0입니다.


<ipython-input-100-b5f0529bd5f1>:4: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  sqrt_num = sqrt(num)


## 문제4) 두 문자열을 입력받아 연결하여 출력하세요.

In [ ]:
str1 = input("첫번째 문자 입력")
str2 = input("두번째 문자 입력")

def connect_str(str1, str2):
  result = str1 + str2

  return print(f"첫번째 문자는 {str1}, 두번째 문자는 {str2} \n 연결하면 {result}입니다.")

connect_str(str1, str2)

첫번째 문자 입력가
두번째 문자 입력나다
첫번째 문자는 가, 두번째 문자는 나다 
 연결하면 가나다입니다.


## 문제5) 두 불리언 값에 대해 AND 연산을 수행하여 결과를 출력하세요.

In [ ]:
import sys

bool1 = input("첫 번째 불리언 값을 입력하세요 : ")
if bool1 == 'True':
  bool1 = True
elif bool1 == 'False':
  bool1 = False
else :
  print("값은 True 혹은 False값만 입력해주세요. 프로그램이 종료됩니다.")
  sys.exit(1)

bool2 = input("두 번째 불리언 값을 입력하세요 : ")
if bool2 == 'True':
  bool2 = True
elif bool2 == 'False':
  bool2 = False
else :
  print("값은 True 혹은 False값만 입력해주세요. 프로그램이 종료됩니다.")
  sys.exit(1)

result_AND = bool1 and bool2
result_OR = bool1 or bool2

print(f"boo1 입력값 : {bool1}, bool2 입력값 : {bool2}, AND 연산 결과 : {result_AND}, OR 연산 결과 : {result_OR}")

첫 번째 불리언 값을 입력하세요 : True
두 번째 불리언 값을 입력하세요 : False
boo1 입력값 : True, bool2 입력값 : False, AND 연산 결과 : False, OR 연산 결과 : True


## 문제6) 주어진 두 숫자를 비교하여 큰 숫자를 출력하세요.

In [ ]:
num1 = float(input("첫 번째 숫자를 입력하세요 : "))
num2 = float(input("두 번째 숫자를 입력하세요 : "))

if num1 > num2:
  print("큰 숫자: ", num1)
elif num1 < num2:
  print("큰 숫자 : ", num2)
else:
  print("두 값은 동일합니다.")

첫 번째 숫자를 입력하세요 : 1
두 번째 숫자를 입력하세요 : 1
두 값은 동일합니다.


## 문제7) 사용자로부터 입력받은 숫자가 짝수인지 홀수인지 판별하여 출력하세요.

In [ ]:
# 나머지 연산 사용
def even_odd_using_modulo(num):
    if num % 2 == 0:
        return "짝수"
    else:
        return "홀수"

number = 16
result = even_odd_using_modulo(number)
print(f"{number}는 {result}입니다.")

16는 짝수입니다.


In [ ]:
# 비트 연산 사용
def even_odd_using_bitwise(num):
    if num & 1 == 0:
        return "짝수"
    else:
        return "홀수"

number = 24
result = even_odd_using_bitwise(number)
print(f"{number}는 {result}입니다.")

24는 짝수입니다.


In [ ]:
# 리스트 사용
def even_odd_using_list(num):
    parity = ["짝수", "홀수"]
    return parity[num % 2]

number = 9
result = even_odd_using_list(number)
print(f"{number}는 {result}입니다.")


9는 홀수입니다.


In [ ]:
# 빌트인 함수 활용
# divmod : 나눗셈의 몫과 나머지를 한 번에 계산
def even_odd_using_divmod(num):
    _, remainder = divmod(num, 2)
    if remainder == 0:
        return "짝수"
    else:
        return "홀수"

# 사용 예시
number = 42
result = even_odd_using_divmod(number)
print(f"{number}는 {result}입니다.")

42는 짝수입니다.


In [ ]:
# 조건 표현식(삼항 연산자)을 이용
def even_odd_using_conditional(num):
    return "짝수" if num % 2 == 0 else "홀수"

number = 33
result = even_odd_using_conditional(number)
print(f"{number}는 {result}입니다.")

33는 홀수입니다.


## 문제8) 세 개의 숫자를 입력받고, 가장 큰 숫자를 출력하세요.

In [ ]:
import sys

try:
  num1 = float(input("첫 번째 숫자를 입력하세요 : "))
  num2 = float(input("두 번째 숫자를 입력하세요 : "))
  num3 = float(input("세 번째 숫자를 입력하세요 : "))
except:
  print("값은 숫자만 입력해주세요. 프로그램이 종료됩니다.")
  sys.exit(1)

result = max(num1, num2, num3)
print(f"가장 큰 수는 {result}입니다.")

첫 번째 숫자를 입력하세요 : 1
두 번째 숫자를 입력하세요 : 2
세 번째 숫자를 입력하세요 : 3
가장 큰 수는 3.0입니다.


## 문제9) 사용자로부터 입력받은 숫자에 10을 더한 후 결과를 출력하세요.

In [ ]:
num = float(input("숫자 입력"))

def plus_10(num):
  input_num = num
  num += 10
  return print(f"입력받은 숫자 : {input_num}, 10을 더한 후 결과 : {num}")

plus_10(num)

숫자 입력100
입력받은 숫자 : 100.0, 10을 더한 후 결과 : 110.0


<hr>

# 2. 연산자(심화문제)

## 예제 1 : 데이터 전처리 - 스케일링

- 다음 내용의 코드를 변수의 의미에 따라 직독직해서 공유해봅시다.

In [ ]:
import numpy as np

# 데이터 셋
# numpy 모듈을 사용하여 배열을 만들어 data 변수에 저장
data = np.array([100, 200, 300, 400, 500], dtype=float)

# 데이터 스케일링 (표준화)
# data의 평균값을 mean, 분산을 std에 저장
mean = np.mean(data)
std = np.std(data)

# data 배열에 저장해둔 평균값 -, 분산 / 적용
data -= mean
data /= std

## 예제 2 : 손실 함수 계산 - MSE

- 다음 내용의 코드를 변수의 의미에 따라 직독직해서 공유해봅시다.

In [ ]:
# 실제 값과 예측 값
# actual과 predicted에 배열 생성
actual = np.array([1.0, 2.0, 3.0])
predicted = np.array([1.1, 1.9, 3.2])

# MSE 계산
# 배열 - 연산 작업 후 제곱의 평균 구하기
mse = np.mean((actual - predicted) **2)
print(mse)

0.020000000000000035


## 예제 3 : 가중치 업데이트 - 경사 하강법

- 다음 내용의 코드를 변수의 의미에 따라 직독직해서 공유해봅시다.

In [ ]:
# 가중치 초기화
# weights, gradient 배열 생성
weights = np.array([0.5, -0.5])
learning_rate = 0.01
gradient = np.array([0.1, -0.2])

# 가중치 업데이트
weights -= learning_rate * gradient
# weights = weights - learning_rate * gradient

## 예제 4 : 활성화 함수 적용 - ReLU

- 다음 내용의 코드를 변수의 의미에 따라 직독직해서 공유해봅시다.

In [ ]:
# 입력값
inputs = np.array([-1.0, 2.0, -0.5, 3.0])

# ReLU 활성화 함수 적용
inputs = np.maximum(0, inputs)
print(inputs)

# maximum(매개변수1, 매개변수2) = 매개변수1보다 큰 매개변수2는 유지, 아닐경우 매개변수1로 대체
# ReLU = 모델 학습 진행시 데이터가 모델에 별다른 영향을 주지 않을 data를 삭제하기 위함

[0. 2. 0. 3.]


## 예제 5 : 최종

- 다음 내용의 코드를 변수의 의미에 따라 직독직해서 공유해봅시다.

In [ ]:
import numpy as np

# 예측값과 실제값
y_true = np.array([3, -0, 2, 7])
y_pred = np.array([2.5, 0, 2, 8])

# 샘플 수
n = len(y_true)

# MSE (Mean Absolute Error)
rmse = sum(abs(y_true - y_pred)) / n
print(f"MSE:{rmse}")

# RMSE(Root Mean Squared Error)
rmse = (sum((y_true - y_pred) **2)/n) **0.5

# RMSLE(Root Mean Squared Logarithmic Error)
# 로그를 계산할 때 Log(0)이 발생하지 않도록 1을 더함
log_true = np.log(y_true + 1)
log_pred = np.log(y_pred + 1)
rmsle = (sum((log_true - log_pred)**2)/n)**0.5
print(f"RMSLE: {rmsle}")

MSE:0.375
RMSLE: 0.08902735015807975
