<a href="https://colab.research.google.com/github/YugyeongJo/SeSAC_Python_Study/blob/main/docs/01_Python_Basic(Variable)_0701.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python 기초

<목차>
1. 변수
2. 연산자
3. 제어문
4. 함수
5. 자료형 1
6. 자료형 2
7. 정규표현식
8. 판다스
9. 시각화
10. 파일 입출력

<hr>

# 1. 변수(문법)

## 변수(객체) 주소 확인

In [ ]:
x = 100
print(x)

100


In [ ]:
print(id(x))

139088830647632


## 변수

- 변수(Variable) : 프로그램이 실행되는 동안 상황에 따라 변하는 값을 저장
- 변수가 없다면 : 코드 내에서 매번 값을 지정해주면 코드를 작성하거나 수정하기 어려움
- 변수 사용 이점 : 변수는 코드 내에서 자료를 일관성 있게 사용하고 관리하기 위해서 이름(identifier)을 부여해 다른 변수 또는 자료와 구분해서 사용할 수 있도록 함.

### 변수 선언
- 값을 저장할 수 있는 변수를 만드는 것
- 변수 선언을 위해서는 변수에 어떤 종류의 값이 저장되어야 하는지 알리기 위한 타입이 있어야 함
- 파이썬은 변수를 선언하기 위한 타입이 없으므로 변수 선언 과정이 없음

### 변수 할당
- 어떤 값이 이름을 갖도록 하는 과정
- =연산자를 이용
```
변수명 = 연산결과값
```
- 변수의 이름은 문자, 숫자, 밑줄(_(underscore))문자를 포함하며, 대/소문자를 구분함
- 숫자로 시작할 수 없으며, 밑줄 문자를 제외한 특수문자, 공백, 문장부호 등은 사용 불가
- 파이썬의 예약어는 사용할 수 없음(ex. class, def 등)
- 사용 중인 내장 함수나 모듈 이름 등은 사용 지양(ex. id, list, print)

#### 변수 할당 방식

- 할당(Assignment)은 변수에 값을 저장하는 것을 의미
- 파이썬에서 변수에 값을 저장하기 위해서는 할당연산자 =(동등 기호)를 사용
- 변수는 여러개 할당 가능
- 변수에 값의 할당 작업은 순차적으로 발생하는 것은 아님

##### 동시할당(Simultaneous Assignment)
- 여러 변수에 값을 한번에 할당하는 방식

##### 순차적할당(Sequential Assignment)
- 변수에 값을 한 번에 하나씩, 순서대로 할당하는 방식

In [ ]:
# 변수 할당
a = 10
print(a)

10


In [ ]:
# 동시할당
a, b = 10, 20
a, b = b, a+b

In [ ]:
# 순차적 할당
a, b = 10, 20
a = b
b = a+b

In [ ]:
a, b

(20, 40)

## Method 함수

### 메서드 설명 함수

- 함수의 도움말을 얻기 위해 사용하는 함수

```
help(메서드명)
```

In [ ]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



### 출력 함수

#### print 메서드
```
print(객체, sep='', end='\n', file=None, flust=False)
```

- end 매개변수 : 기본값:"\n"(줄바꿈 문자), 출력 내용의 끝에 추가되는 문자열을 지정
- sep 매개변수 : 기본값: 공백 분자(""), 여러 값/인수를 출력할 때 각 값 사이에 사용되는 구분 문자열을 지정
- file 매개변수 : 기본값:sys.stdout(표준 출력), 출력 내용을 특정 파일로 리디렉션할 때 사용
- flush 매개변수: 기본값: False, 출력 버퍼를 즉시 비우고 출력을 강제로 플러시할지 여부를 지정

In [ ]:
print('Hello', 'World')

Hello World


In [ ]:
print('Hello', 'World', sep='.')

Hello.World


In [ ]:
print('Hello', 'World', sep='\t')
# \t 는 탭문자

Hello	World


In [ ]:
print('Hello')
print('World')

Hello
World


In [ ]:
print('Hello', end='\t')
print('World')

Hello	World


In [ ]:
name = '홍길동'
age = 20

In [ ]:
print(name, '님의 나이는 ', age, '세입니다.', sep='')

홍길동님의 나이는 20세입니다.


In [ ]:
print(f"{name}님의 나이는 {age}세입니다.")

홍길동님의 나이는 20세입니다.


### 입력 함수

- 사용자로부터 값을 입력 받기 위한 함수, 입력 받은 값은 항상 문자열임

#### input 메서드
```
변수명 = input()
```

** input으로 받은 값은 str이기 때문에 숫자로 인식하고 싶을때에는 int or float로 datatype 변경 필요

In [ ]:
first_number = int(input('첫 번째 숫자 : '))

첫 번째 숫자 : 20


In [ ]:
second_number = int(input('두 번째 숫자 : '))

두 번째 숫자 : 30


In [ ]:
print(first_number + second_number)

50


## DataType 기본자료형
- 프로그래밍 언어들은 변수가 가져야 할 값의 크기, 형식, 범위 등에 따라서 값의 유형을 정해 놓고 사용
- 자료형은 프로그래밍 언어에서 정수, 실수, 논리 등 여러 종류의 자료(데이터)가 어떤 값을 가질 수 있는지에 대해 알려주는 속성
- 자료형에 따라 저장할 수 있는 값의 범위(크기)와 값을 저장하는 방식이 달라짐
- 자료형에 따라 수행할 수 있는 명령들이 달라질 수 있음

### DataType의 종류
- 숫자형(int, float, complex)
- 문자형(str)
- 이스케이프 문자
- 논리형(bool)

### 숫자형
 + 정수(int) : 소수점이 없는 정수
 + 실수(float) : 부동소수점, 소수점이 있는 숫자
 + 복소수(complex)

In [ ]:
a = 10
type(a)

int

### 문자형
 + 단일문자와 문자열을 구분하지 안음
 + 겹따옴표("와") 또는 홑따옴표('와 ')로 묶어서 사용
 + 여러 줄 문자열은 겹따옴표 3개("""와 """) 또는 홑따옴표 3개('''와 ''')를 사용

In [ ]:
name = "조유경"
address = "서울시 구로구"
print(name, address)

조유경 서울시 구로구


#### 문자열 string 연산

- 문자열과 문자열을 +(덧셈)하면 문자열을 연결
- 문자열을 공백으로 연결해도 문자열을 연결
- 문자열과 숫자를 *(곱셈) 연산 하면 문자열을 곱셈한 숫자만큼 반복



In [ ]:
"Hello"+"World"

'HelloWorld'

In [ ]:
"Hello" "World"

'HelloWorld'

In [ ]:
2*"Hello"

'HelloHello'

#### 문자열 슬라이싱

- 문자열[index] 형식으로 문자열에서 지정한 위치(index)의 문자를 뽑아낼 수 있음
- 첫 문자의 인덱스가 0, 음수는 맨 뒤의 문자부터 의미(-1 인덱스는 가장 마지막 문자)
 + s[a:n] : index a번째부터 n-1번쩨까지의 문자열
 + s[:] : index 0번째(처음)부터 끝까지의 문자열
 + s[::n] : index 0번째(처음)부터 끝까지의 문자열(n번씩 띄어서)

In [ ]:
"Python"[0]

'P'

In [ ]:
"Python"[3]

'h'

In [ ]:
# 마지막 문자 출력
S = "Today fine"
S[9]

'e'

In [ ]:
# 첫번째 문자 출력
S[-10]

'T'

In [ ]:
# 구간 출력
S[3:8]

'ay fi'

In [ ]:
# 띄어넘어가며 구간 출력
S[::2]

'Tdyfn'

### 이스케이프 문자
 + \n : 줄바꿈
 + \t : 탭
 + \r : 리턴(행의 첫 번째 열로 돌아옴)
 + \0 : 널(null)
 + \\ : \문자 표시
 + \' : '(홑따옴표) 문자 표시
 + \" : "(곁따옴표) 문자 표시

In [ ]:
print("Hello\nWorld")

Hello
World


In [ ]:
print("Hello\tWorld")

Hello	World


In [ ]:
print("Hello\rWorld")

World


In [ ]:
print("Hello\0World")

HelloWorld


In [ ]:
print("Hello\\World")

Hello\World


In [ ]:
print("Hello\'World")

Hello'World


In [ ]:
print("Hello\"World")

Hello"World


### 논리형(Bool)
- True 또는 False 값을 가짐(true 또는 TRUE를 논리 값으로 사용 못함)
- True로 판별되는 경우는 False로 판별되는 경우를 제외하고 모든 경우

In [ ]:
if 0:
  print(True)
else:
  print(False)

False


In [ ]:
if 0+0:
  print(True)
else:
  print(False)

False


In [ ]:
if 0.0:
  print(True)
else:
  print(False)

False


In [ ]:
if '':
  print(True)
else:
  print(False)

False


### 자료형 타입 확인
- 자료형의 type을 확인하기 위해 사용

```
type()
```

In [ ]:
type(120)

int

In [ ]:
type(3.14)

float

In [ ]:
type('hello')

str

In [ ]:
type(True)

bool

## List 리스트
- []를 이용해서 만들며 여러 개 값을 하나의 변수에 저장/관리할 수 있음

### 인덱스
- 각 요소의 위치, 인덱스는 0부터 시작(첫 항목의 인덱스는 0)

### 슬라이싱
- 부분 데이터셋을 뽑아내는 것. 인덱스를 이용해서 쓰기와 읽기를 지원

In [ ]:
fruits = ["banana", "apple", "orange", "grape"]
print(fruits)

['banana', 'apple', 'orange', 'grape']


In [ ]:
numbers = [1,2,3,4,5]
print(numbers)

[1, 2, 3, 4, 5]


In [ ]:
my_list = []

if not bool(my_list):
  print("The list is empty")
else:
  print("The list is not empty")

The list is empty


### range()
- 연속한 값을 갖는 리스트를 생성하는 메서드

```
range([from,]to[,by]
```

In [ ]:
list(range(-10, 10, 2))

[-10, -8, -6, -4, -2, 0, 2, 4, 6, 8]

### 다차원 리스트
- []안에 []를 넣으면 차원이 증가

```
변수명 = [...]: 1차원 리스트
변수명 = [[...], ...]: 2차원 리스트
변수명 = [[[...], ...], ...]: 3차원 리스트
...
```

In [ ]:
numbers_2d_v = [[1,2,3], [10,20,30], [1,3,5,7,9], [2,4,6,8]]
print(numbers_2d_v)

[[1, 2, 3], [10, 20, 30], [1, 3, 5, 7, 9], [2, 4, 6, 8]]


### List 연산

- '+' : 두 리스트를 연결함
- '*' : 리스트를 곱한 수 만큼 반복

In [ ]:
numbers=[1,2,3,4,5]
new_numbers = numbers+numbers
new_numbers

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
new_numbers_01 = 3*numbers
new_numbers_01

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

### List 관련 Method

- len() : 길이(항목의 수)
- min(), max() : 최솟값, 최댓값
- append() : 단일 항목을 맨 뒤에 추가함, 리스트를 append 하면 리스트가 추가됨
- extend() : 리스트를 항목별로 맨 뒤에 추가
- insert() : 지정한 인덱스 위치에 삽입

In [ ]:
numbers_2d_v[0]

[1, 2, 3]

In [ ]:
len(numbers_2d_v)

4

In [ ]:
min(numbers_2d_v)

[1, 2, 3]

In [ ]:
max(numbers_2d_v)

[10, 20, 30]

In [ ]:
numbers.append(10)
numbers

[1, 2, 3, 4, 5, 10]

In [ ]:
numbers.append([20,30,40,50])
numbers

[1, 2, 3, 4, 5, 10, [20, 30, 40, 50], [20, 30, 40, 50]]

In [ ]:
numbers = [1,2,3,4,5]
numbers.extend([10,20,30,40,50])
numbers

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [ ]:
numbers.insert(5,100)
numbers

[1, 2, 3, 4, 5, 100, 10, 20, 30, 40, 50]

In [ ]:
# 다차원리스트 행렬
matrix = [
    [1,2,3]
    , [4,5,6]
    , [7,8,9]
]
print(matrix[0][1])

2


In [ ]:
numbers=[1,2,3,4,5,6,7,8,9,10]
numbers[2:4]

[3, 4]

## Tuple 튜플
- 튜플(tuple)은 소괄호('('와 ')')를 이용해 생성
- 튜플은 읽기 전용, 속도가 빨라 수정이 필요 없는 배열 형태의 데이터 타입에 사용
- 데이터를 수정할 수 없기 때문에 제공되는 함수가 많지 않음

In [ ]:
numbers1 = (1,2,3,4,5)
type(numbers1)

tuple

In [ ]:
numbers_2d = ((1,2,3), (4,5,6))
numbers_2d

((1, 2, 3), (4, 5, 6))

## Dictionary 딕셔너리 {key:value}
- 중괄호('{'와 '}')를 이용해서 딕셔너리 생성, 키(key)와 값(value)의 쌍으로 구성된 자료
- 키는 유일(unique)해야 함
- 키에 리스트를 사용할 수 없음, 튜플 타입은 사용할 수 있음
- 값은 중복이 가능하며 모든 타입이 가능
- 키 목록에 없는 데이터를 사용하여 참조하면 에러가 발생, 인덱스를 이용한 참조는 지원안함

In [ ]:
# 딕셔너리 생성
example_dict = {'name':'Alice', 'age': 25, 'city':'Seoul'}
example_dict

{'name': 'Alice', 'age': 25, 'city': 'Seoul'}

### Dictionary 관련 Method
- items() 메소드
 + 딕셔너리의 모든 키-값 쌍을 튜플 형태로 반환
- keys() 메소드
 + 딕셔너리의 모든 키를 반환
- values() 메소드
 + 딕셔너리의 모든 값을 반환

In [ ]:
print("Items:")
for key, value in example_dict.items():
  print(f"Key:{key}, Value:{value}")

Items:
Key:name, Value:Alice
Key:age, Value:25
Key:city, Value:Seoul


In [ ]:
print("Keys:")
for key in example_dict.keys():
  print(f"Key:{key}")

Keys:
Key:name
Key:age
Key:city


In [ ]:
print("Values:")
for value in example_dict.values():
  print(f"Value:{value}")

Values:
Value:Alice
Value:25
Value:Seoul


<hr>

# 1. 변수(기본문제)

## 문제1) 사용자의 이름을 변수에 저장하고, 저장된 이름을 출력하세요.

In [ ]:
name = input('이름을 입력하세요')
print("사용자 이름 : ", name)

이름을 입력하세요조유경
사용자 이름 :  조유경


## 문제2) 세 개의 변수를 사용하여 사용자의 이름, 나이, 성별을 저장하고 출력하세요.

In [ ]:
name = input('이름을 입력하세요')
age = input('나이를 입력하세요')
gender = input('성별을 입력하세요')
print(f"""
사용자 이름: {name}
나이 : {age}
성별 : {gender}ㅇ
""")

이름을 입력하세요조유경
나이를 입력하세요28
성별을 입력하세요ㅕ

사용자 이름: 조유경
나이 : 28
성별 : ㅕ



## 문제3) 두 변수의 값을 교환하고, 교환된 변수의 값을 출력하세요.

In [ ]:
a = input("첫번째 입력")
b = input("두번째 입력")
# 동시 할당 방식
a, b = b, a
print("첫1번째 값 출력 : ", b)
print("두번째 값 출력 : ", a)
# 순차적 할당 방식으로 값을 교환하려고 하면 변수를 하나 더 지정해서 해야함. 1

첫번째 입력10
두번째 입력00
첫1번째 값 출력 :  10
두번째 값 출력 :  00


## 문제4) 사용자로부터 입력받은 두 개의 숫자를 더한 결과를 변수에 저장하고 출력하세요.

In [ ]:
while True:
    try:
        num1 = int(input("첫번째 숫자 입력: "))
        break  # 숫자가 제대로 입력되면 반복문을 종료합니다
    except ValueError:
        print("숫자만 입력하세요.")

while True:
    try:
        num2 = int(input("두번째 숫자 입력: "))
        break  # 숫자가 제대로 입력되면 반복문을 종료합니다
    except ValueError:
        print("숫자만 입력하세요.")

add = num1 + num2
print(f"두 숫자의 합: {add}")

첫번째 숫자 입력: ㅇ
숫자만 입력하세요.
첫번째 숫자 입력: ㅇ
숫자만 입력하세요.
첫번째 숫자 입력: 10
두번째 숫자 입력: ㅇ
숫자만 입력하세요.
두번째 숫자 입력: ㅇ
숫자만 입력하세요.
두번째 숫자 입력: 20
두 숫자의 합: 30


## 문제5) 다음 불리언 값 (True 또는 False)을 변수에 저장하고 출력하세요.

In [ ]:
import random

bool_variable = random.choice([True, False])

print(f"불리언 값은 {bool_variable}입니다.")

불리언 값은 True입니다.


## 문제6) 두 숫자를 곱한 결과를 변수에 저장하고 출력하세요. (숫자는 자유롭게 선택)

In [ ]:
import random

num1 = random.randint(1, 10)  # 1부터 10 사이의 정수 중 랜덤으로 선택
num2 = random.randint(1, 10)  # 1부터 10 사이의 정수 중 랜덤으로 선택

multiple = num1 * num2
print(f"랜덤 숫자 1 : {num1}, 랜덤 숫자 1 : {num2}, 랜덤의 두 숫자의 곱: {multiple}")

랜덤 숫자 1 : 7, 랜덤 숫자 1 : 4, 랜덤의 두 숫자의 곱: 28


## 문제7) 다음 리스트를 변수에 저장하고, 해당 변수의 내용을 출력하세요

In [ ]:
import random

# 사용자가 지정한 범위에서 랜덤한 정수 5개로 구성된 리스트 생성
start = 0
end = 20
custom_range_list = [random.randint(start, end) for _ in range(5)]
print(f"리스트 출력 : {custom_range_list}")

리스트 출력 : [17, 0, 20, 6, 13]


## 문제8) 사용자로부터 입력받은 문자열을 변수에 저장하고 출력하세요

In [ ]:
# 단순 변수 저장
str = input("값을 입력하세요")
print(f"입력값 출력 : {str}")

In [ ]:
# 입력값 list 저장 후 출력
list_str = []
while True:
  str = input("값을 입력하세요(입력을 중단하고 싶을 경우 x를 입력해주세요)")
  if str != "x":
    list_str.append(str)
  else:
    break
print(f"입력값 출력 : {list_str}")

값을 입력하세요(입력을 중단하고 싶을 경우 x를 입력해주세요)x
입력값 출력 : []


## 문제9) 두 변수에 각각 "Hello"와 "world"를 저장하고, 두 변수를 합쳐서 출력하세요

In [ ]:
first_str = "Hello"
second_str = "world"

result = first_str+" "+second_str
print(f"결과는 : {result}")

결과는 : Hello world


<hr>

# 1. 변수(심화문제)

## 문제 : 다음 코드를 확인하고 최대한 해석하여 댓글에 붙여  봅시다.

import numpy as np
<!-- 연산작업을 수행하기 위해 파이썬에서 제공하는 넘파이 패키지를 임포트하여 np라는 alias를 붙여줌 -->

from sklearn.model_selection
import train_test_split
<!-- 사이킷런 라이브러리에 존재하는 model_selection 서브 모듈의 train_test_split(학습시킬 dataset에서 train dataset을 만들어주기 위한)함수를 사용하기 위해 임포트함 -->

from sklearn.linear_model
import LogisticRegression
<!-- 사이킷런 라이브러리에 존재하는 linear_model 서브 모듈의 LogisticRegression(분류모델을 만들기 위한 작업들을 수행하는)클래스를 사용하기 위해 임포트함 -->

from sklearn.metrics
import accuracy_score
<!-- 사이킷런 라이브러리에 존재하는 metrics 서브 모듈의 accuracy_score(모델의 정확도를 평가하기 위한 작업들을 수행하는)를 사용하기 위해 임포트함-->


# 데이터 생성
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([0, 0, 1, 1])
<!-- 넘파이의 배열을 통해 X와 y 데이터 생성 -->


# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X,
y, test_size=0.25)
<!-- 생성된 X와 y 데이터를 훈련 데이터인 X_train, y_train 그리고 테스트 데이터인 X_test, y_test에 쪼개서 할당해줌 -->


# 모델 생성 및 학습
model = LogisticRegression()
model.fit(X_train, y_train)
<!-- model이라는 변수에 이진분류 작업을 수행하도록 하는 LogisticRegression() 메서드를 할당해주고, 각각 할당해둔 훈련 데이터들을 사용하여 model을 학습시켜줌 -->

# 예측 및 평가
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')
<!-- 학습시킨 model의 성능을 할당해준 test 데이터를 사용하여 예측하고 모델 성능의 정확도를 편가하여 정확도를 출력함 -->

<hr>

# 1. 변수(예제)

## 1) 기본 변수

- 간단한 데이터 타입을 저장하는데 사용
- ex) 정수, 실수, 문자열 등

In [1]:
# 정수 변수
num_epochs = 100

In [2]:
# 실수 변수
learning_rate = 0.01

In [3]:
# 문자열 변수
activation_function = 'relu'

## 2) 리스트와 배열

- 리스트와 배열은 여러 개의 값을 저장하는데 사용
- 머신러닝과 딥러닝에서는 Numpy 배열을 많이 사용

In [4]:
# 파이썬 리스트
layers = [64,128,256]

In [5]:
# Numpy 배열
import numpy as np
weights = np.array([0.1, 0.2, 0.3])

## 3) 딕셔너리

- 딕셔너리는 키-값 쌍을 저장하는데 사용
- 모델의 하이퍼파라미터를 저장할 때 유용

In [6]:
# 파이썬 딕셔너리
model_params = {
    'learning_rate': 0.01
    , 'num_epochs':100
    , 'batch_size': 32
}

## 4) Pandas DataFrame

- Pandas DataFrame은 테이블 형식의 데이터를 저장하고 조작하는데 사용
- 머신러닝에서 데이터 전처리에 자주 사용

In [8]:
# Pandas DataFrame
import pandas as pd

# 데이터프레임 생성
data = {
    'feature1': [1,2,3]
    , 'feature2': [4,5,6]
    , 'label': [0,1,0]
}
df = pd.DataFrame(data)
df

feature1  feature2  label
0         1         4      0
1         2         5      1
2         3         6      0

## 5) TensorFlow와 Keras 변수

- 딥러닝에서는 TensorFlow와 Keras를 사용하여 텐서를 정의하고 모델을 구성

In [10]:
# TensorFlow
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [11]:
# Keras 모델
model = Sequential([
    Dense(64, activation='relu', input_shape=(10,))
    , Dense(1, activation='sigmoid')
])
model

## 실습
학습한 내용 중 다음 내용에 대해 정리하고 다양한 예시코드를 작성하여 공유해봅시다.

- 기본 자료형 : Int, float, string, bool
- string의 인덱스 추출
- 리스트, 튜플, 딕셔너리

### 기본 자료형 : Int, float, string, bool

In [13]:
# Int : 데이터 자료형 중 숫자형에 해당하며 정수를 의미
Int = 10
type(Int)

int

In [15]:
# float : 데이터 자료형 중 숫자형에 해당하며 부동소수점, 소수점이 있는 숫자를 의미
Float = 3.142592
type(Float)

float

In [16]:
# string : 데이터 자료형 중 문자형에 해당하며 문자를 의미
str = '조유경'
type(str)

str

In [18]:
# bool : 데이터 자료형 중 논리형에 해당하며 True 또는 False의 값을 가지는 형태를 의미
Bool = True
type(Bool)

bool

### string의 인덱스 추출

In [19]:
str

'조유경'

In [20]:
str[0]

'조'

In [21]:
str[2]

'경'

In [22]:
str[-1]

'경'

In [23]:
str[-3]

'조'

In [24]:
str[:]

'조유경'

In [25]:
str[::]

'조유경'

In [26]:
str[::-1]

'경유조'

In [27]:
str[::2]

'조경'

### 리스트, 튜플, 딕셔너리

In [34]:
# 리스트 : []를 이용해서 여러 개의 값을 하나의 변수에 저장하는 것으로 저장/관리에 유용
list_variable = [1,2,3,'가','나','다']
type(list_variable)

list

In [35]:
# 리스트 인덱스 추출
list_variable[1::-2]

[2]

In [40]:
# 튜플 : ()를 이용해서 수정이 필요 없는(읽기 전용) 배열 형태로 변수에 저장하는 것으로 속도가 빨라서 유용
tuple_variable = (1,3)
type(tuple_variable)

tuple

In [43]:
# 튜플 인덱스 추출
tuple_variable[1]

3

In [50]:
# 딕셔너리 : {}를 이용해서 키(key)와 값(value)의 쌍으로 변수에 저장하는 것
# 키는 유일해야하면서 리스트를 사용할 수 없음 but, 튜플은 사용가능
# 값은 중복이 가능하며 모든 타입이 가능
# 인덱스를 이용한 참조는 불가능
dict_variable = {
    'name':'조유경'
    , 'age':28
}
type(dict_variable)

dict

In [51]:
# items() 메서드 사용
dict_variable.items()

dict_items([('name', '조유경'), ('age', 28)])

In [52]:
# keys() 메서드 사용
dict_variable.keys()

dict_keys(['name', 'age'])

In [53]:
# values() 메서드 사용
dict_variable.values()

dict_values(['조유경', 28])

<hr>

# 1. 변수(심화예제)

In [65]:
# 환경 세팅
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [73]:
# 데이터 생성
X = np.array([[1,2], [2,3], [3,4], [4,5]])
y = np.array([0,0,1,1])
X, y

(array([[1, 2],
        [2, 3],
        [3, 4],
        [4, 5]]),
 array([0, 0, 1, 1]))

In [74]:
# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
X_train, X_test, y_train, y_test

(array([[4, 5],
        [2, 3],
        [3, 4]]),
 array([[1, 2]]),
 array([1, 0, 1]),
 array([0]))

In [75]:
# 모델 생성 및 학습
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [76]:
# 예측 및 평가
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 1.0
