<a href="https://colab.research.google.com/github/YugyeongJo/SeSAC_Python_Study/blob/main/docs/06_Python_Basic(Datatype_List2)_0708_0709.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python 기초

<목차>
1. 변수
2. 연산자
3. 제어문
4. 함수
5. 자료형 1
6. 자료형 2
7. 정규표현식
8. 판다스
9. 시각화
10. 파일 입출력

<hr>

# 5. 자료형 2

## 튜플(Tuple)
- 소괄호 ()를 이용해 생성
- 읽기 전용, 속도가 빨라 수정이 필요 없는 배열 형태의 데이터 타입에 사용
- 데이터를 수정할 수 없기 때문에 제공되는 함수가 많지 않음
- 튜플의 불변성, 패킹/언패킹 기능, 그리고 여러 값을 하나의 단위로 처리하기 때문에 데이터가 변경되지 않아야 하는 경우(ex. 딕셔너리 키)나 성능이 중요한 경우 튜플을 사용
- 데이터의 무결성을 유지, 복합 키가 필요, 함수에서 여러 값을 반환할 때 특히 유용

In [ ]:
numbers1 = (1, 2, 3, 4, 5)
type(numbers1)

tuple

In [ ]:
numbers2 = (1, )
type(numbers2)

tuple

In [ ]:
numbers_2d = ((1, 2, 3), (4, 5, 6))
numbers_2d

((1, 2, 3), (4, 5, 6))

### 튜플관련 메서드
- 리스트와 튜플은 모두 시퀀스 타입이지만, 리스트는 가변(mutable)이고, 튜플은 불변(immutable) 가능한 메서드의 차이
- 리스트는 다양한 수정 메서드(append, extend, insert, remove, pop, clear, sort, revers 등)를 가짐
- 튜플은 불변이기 때문에 내용을 수정하는 메서드가 없음

|방법|설명|비고|
|--|--|--|
|tupleData = ()|튜플을 만들어 줌||
|len(tupleDate)|튜플의 항목 수를 반환||
|min(tuple), max(tuple)|튜플에서 가장 작은 값(min)과 가장 큰 값(max)을 반환||
|tupleData.count(value)|튜플에서 value의 개수를 반환||
|tupleData.index(value, position)|position 위치 이후에서 value가 있는 인덱스를 반환||


In [ ]:
def calculate_statistics(numbers):
  mean = sum(numbers) / len(numbers)
  variance = sum((x-mean)**2 for x in numbers) / len(numbers)
  return mean, variance

# 튜플로 반환된 값을 함수 인수로 사용
numbers = [1, 2, 3, 4, 5]
mean, variance = calculate_statistics(numbers)
print(f"Mean : {mean}, Variance: {variance}")

Mean : 3.0, Variance: 2.0


In [ ]:
def print_statistics(statistics):
  mean, variance = statistics
  print(f"Mean: {mean}, Variance:{variance}")

# 튜플을 인수로 전달
print_statistics((mean, variance))

Mean: 3.0, Variance:2.0


In [ ]:
# 함수에서 여러 값 반환
def get_user_info():
  return("Alice", 30, "alice@example.com")

name, age, email = get_user_info()
print(f"Name:{name}, Age:{age}, Email:{email}")


Name:Alice, Age:30, Email:alice@example.com


In [ ]:
# 좌표 표현
def calculate_distance(point1, point2):
  return ((point1[0] - point2[0])**2 + (point1[1] - point2[1])**2)**0.5

point_a = (0, 0)
point_b = (3, 4)
distance = calculate_distance(point_a, point_b)
print(f"Distance : {distance}")

Distance : 5.0


In [ ]:
# 딕셔너리의 키로 사용
student_grades = {
    ("John", "Doe"): 85
    , ("Jane", "Smith"): 92
    , ("Bob", "Johnson"): 78
}

print(student_grades[("Jane", "Smith")])

92


In [ ]:
# 네임드 튜플 사용
from collections import namedtuple

Person = namedtuple('Person', ['name', 'age', 'city'])
alice = Person("Alice", 30, "New York")
print(f"{alice.name} is {alice.age} years old and lives in {alice.city}")

# 네임드 튜플 (named tuple)
# Python의 collections 모듈에서 제공하는 클래스 중 하나로, 튜플과 비슷하지만 필드 이름을 가질 수 있는 튜플
# 이를 통해 코드의 가독성을 높이고, 데이터에 의미 있는 이름을 부여할 수 있다.

Alice is 30 years old and lives in New York


In [ ]:
# 고정된 데이터 집합 표현
DAYS_OF_WEEK = ("Mon", "Tues", "Wedn", "Thur", "Fri", "Sat", "Sun")

def is_weekend(day):
  return day in DAYS_OF_WEEK[-2:]

print(is_weekend("Sat"))

True


In [ ]:
# 함수로 인자 전달
def print_person_info(info):
  name, age, occupation = info
  print(f"{name} is {age} years old and works as a {occupation}")

person_info = ("Charlie", 35, "Engineer")
print_person_info(person_info)

Charlie is 35 years old and works as a Engineer


In [ ]:
# 반복 가능한(iterable) 객체의 언패킹
numbers = (1, 2, 3, 4, 5)
first, *middle, last = numbers
print(f"First: {first}, Middle: {middle}, Last: {last}")

# *연산자 : 변수 할당 시 나머지 값들을 하나의 리스트로 모아주는 역할

First: 1, Middle: [2, 3, 4], Last: 5


In [ ]:
# 데이터베이스 레코드 표현
def fetch_user_records():
  return [
      (1, "Alice", "alice@example.com")
      , (2, "Bob", "bob@example.com")
      , (3, "Charlie", "charlie@example.com")
  ]

for user_id, name, email in fetch_user_records():
  print(f"ID: {user_id}, Name: {name}, Email: {email}")

ID: 1, Name: Alice, Email: alice@example.com
ID: 2, Name: Bob, Email: bob@example.com
ID: 3, Name: Charlie, Email: charlie@example.com


In [ ]:
# 상수 집합 정의
HTTP_STATUS_CODES = (200, 201, 204, 400, 401, 403, 404, 500)

def is_success(status_code):
  return status_code in HTTP_STATUS_CODES[:3]

print(is_success(200))

True


In [ ]:
# 다중 할당
def swap(a, b):
  return b, a

x, y = 10, 20
print(f"Before swap : x = {x}, y = {y}")
x, y = swap(x, y)
print(f"After swap : x = {x}, y = {y}")

# swap함수는 두 인수를 받아서 (b, a)형태의 튜플을 반환
# 여러 값을 콤마로 구분하여 한 줄에 대입할 때 암묵적으로 튜플을 사용

Before swap : x = 10, y = 20
After swap : x = 20, y = 10


In [ ]:
# 함수에서 여러 값 반환
import numpy as np
from sklearn.model_selection import train_test_split

# 데이터와 레이블을 튜플로 변환
dataset = (np.random.rand(100, 5), np.random.randint(0, 2, 100))
print(dataset)

(array([[8.86350141e-01, 6.29711410e-01, 6.40702763e-01, 7.12401667e-01,
        6.40920217e-01],
       [6.19469219e-01, 9.87752401e-01, 2.37972070e-01, 8.85385735e-01,
        8.62786616e-01],
       [8.89738934e-01, 3.86863072e-01, 9.02303484e-01, 7.37638247e-01,
        2.14843874e-01],
       [5.22034525e-01, 6.71339958e-01, 8.34783355e-01, 5.55590044e-01,
        8.01942744e-01],
       [3.02383791e-01, 1.52515464e-01, 1.37665916e-01, 8.89481703e-01,
        8.86199417e-01],
       [3.28205957e-01, 7.87256428e-01, 4.35531859e-01, 1.52574349e-01,
        2.95264357e-01],
       [6.36582643e-01, 8.16208422e-01, 8.29003590e-01, 5.81200435e-01,
        6.01840503e-01],
       [2.75269886e-01, 2.32232308e-01, 3.01916466e-01, 6.44895267e-02,
        9.89637678e-01],
       [8.52155268e-01, 5.69431874e-01, 2.02253348e-01, 2.21244473e-01,
        8.57749208e-01],
       [9.54740421e-02, 1.22241255e-01, 9.72612649e-01, 8.89916945e-01,
        3.97141242e-01],
       [9.78957418e-01, 7.462

In [ ]:
# 함수에서 여러 값 반환
import numpy as np
from sklearn.model_selection import train_test_split

# 데이터와 레이블을 튜플로 표현
dataset = (np.random.rand(100, 5), np.random.randint(0, 2, 100))
dataset

(array([[0.11706091, 0.48112006, 0.85441938, 0.14766423, 0.75474776],
        [0.43205655, 0.88938965, 0.41964157, 0.69410273, 0.08241277],
        [0.59169204, 0.79951991, 0.93045285, 0.26894864, 0.02606374],
        [0.52658362, 0.87597113, 0.06891299, 0.89143295, 0.50033638],
        [0.7647693 , 0.08854715, 0.40312637, 0.40021574, 0.35150246],
        [0.46883876, 0.88601287, 0.50646334, 0.266342  , 0.45572421],
        [0.99291815, 0.0391249 , 0.97257496, 0.5740888 , 0.66275054],
        [0.76502653, 0.61802121, 0.25213353, 0.68444509, 0.3781359 ],
        [0.79757372, 0.73991236, 0.60246612, 0.78891578, 0.92728558],
        [0.57952659, 0.72486368, 0.35598218, 0.51495874, 0.53756811],
        [0.83290123, 0.97407325, 0.69396298, 0.51545644, 0.97243293],
        [0.77960272, 0.85929466, 0.8354576 , 0.90142985, 0.20653094],
        [0.29808408, 0.66695628, 0.06449495, 0.37526076, 0.20449233],
        [0.35253131, 0.87319605, 0.75930477, 0.02078422, 0.69502882],
        [0.65045353,

In [ ]:
# 파라미터 범위 정의
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

# 튜플을 사용하여 파라미터 범위 정의
param_grid = {
    'C' : (0.1, 1, 10)
    , 'kernel' : ('linear', 'rbf')
    , "gamma" : ('scale', 'auto')
}

In [ ]:
# 딕셔너리의 키로 사용
coordinates = {
    (0, 0): "Origin"
    , (1, 2): "Point A"
    , (3, 4): "Point B"
    }
# 특정 좌표의 값을 가져오기
print(coordinates[(1, 2)])

Point A


In [ ]:
# 머신 러닝 사용 사례
import tensorflow as tf

# 예제 데이터
features = [[1, 2], [3, 4], [5, 6]]
labels = [0, 1, 2]

# 튜플을 사용하여 데이터셋 생성
dataset = tf.data.Dataset.from_tensor_slices((features, labels))

for element in dataset:
  print(element)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=2>)


## 딕셔너리(Dictionary)
- 중괄호 {}를 이용해서 딕셔너리 생성. 키(key)와 값(value)의 쌍으로 구성된 자료 구조
- 키는 유일(unique)해야 하며, 키에 리스트를 사용할 수 없음. but, 튜플 타입은 사용 가능
- 값은 중복이 가능하며, 모든 타입이 가능
- 키 목록에 없는 데이터를 사용하여 참조하면 에러가 발생, 인덱스를 이용한 참조는 지원안함
- 관계형 데이터를 다룰 때 특히 유용

|방법|설명|비고|
|--|--|--|
|dictData = {"key":"value", ...}|딕셔너리 생성||
|len(dictData)|딕셔너리 항목의 수를 반환||
|dictData.items()|딕셔너리의 각 항목들을(key, value) 형식의 튜플들로 반환||
|dictData.keys()|딕셔너리의 키(key)들을 반환||
|dictData.values()|딕셔너리의 value들을 반환||

In [ ]:
# 새로운 키-값 쌍 추가(insert) : 키를 지정하고 값을 추가로 입력
my_dict = {'apple':1, 'banana': 2}
my_dict['cherry'] = 3
print(my_dict)

{'apple': 1, 'banana': 2, 'cherry': 3}


In [ ]:
# 기존 키의 값 변경 : 키를 지정하여 기존의 값을 변경
my_dict = {'apple':1, 'banana': 2}
my_dict['apple'] = 5
print(my_dict)

{'apple': 5, 'banana': 2}


In [ ]:
# 여러 개의 새로운 키-값 상 추가(update) : 키와 값을 함께 추가로 입력 (update)
my_dict = {'apple':1, 'banana': 2}
my_dict.update({'cherry': 3, 'date': 4})
print(my_dict)

{'apple': 1, 'banana': 2, 'cherry': 3, 'date': 4}


In [ ]:
# 여러 개 기존 값의 값 update() : 키 값을 지정하여 기존의 값을 변경
my_dict = {'apple':1, 'banana': 2}
my_dict.update({'apple': 5, 'banana': 6})
print(my_dict)

{'apple': 5, 'banana': 6}


In [ ]:
# 기존 데이터의 삭제(del()) : 키 값으로 지정하여 key와 value를 삭제
my_dict = {'apple':1, 'banana': 2, 'cherry': 3}
del my_dict['banana']
print(my_dict)

{'apple': 1, 'cherry': 3}


In [ ]:
# 기존 데이터의 삭제(pop(키 지정)) : 키 값으로 지정하여 키와 값을 삭제하고, 삭제 항목을 리턴값으로 받음
my_dict = {'apple':1, 'banana': 2, 'cherry': 3}
removed_value = my_dict.pop('banana')
print(my_dict)
print(removed_value)

{'apple': 1, 'cherry': 3}
2


In [ ]:
# popitem() : 마지막 자료 삭제, 삭제 항목(key와 value값)을 리턴 값으로 받은
my_dict = {'apple':1, 'banana': 2, 'cherry': 3}
last_item = my_dict.popitem()
print(my_dict)
print(last_item)

{'apple': 1, 'banana': 2}
('cherry', 3)


In [ ]:
dictionary = {'a':1, 'b':2, 'c':3}
value1 = dictionary.pop('b')
print("Value 1: ", value1)

value2 = dictionary.pop('d', 'default')
print("Value : 2", value2)

Value 1:  2
Value : 2 default


In [ ]:
dictionary = {'a':1, 'b':2, 'c':3}
item = dictionary.popitem()
print("Item : ", item)

Item :  ('c', 3)


In [ ]:
# clear()
my_dict = {'apple':1, 'banana': 2, 'cherry': 3}
my_dict.clear()
print(my_dict)

{}


In [ ]:
example_dict = {'name': 'Alice', 'age': 25, 'city': 'Seoul'}

# items() 메서드 사용
print("Items:")
for key, value in example_dict.items():
  print(f"Key: {key}, Value: {value}")

# keys() 메서드 사용
print("\nKeys:")
for key in example_dict.keys():
  print(f"Key: {key}")

# values() 메서드 사용
print("\nValues:")
for value in example_dict.values():
  print(f"Value: {value}")

Items:
Key: name, Value: Alice
Key: age, Value: 25
Key: city, Value: Seoul

Keys:
Key: name
Key: age
Key: city

Values:
Value: Alice
Value: 25
Value: Seoul


In [ ]:
# 사용자 정보 저장 및 접근
user = {
    "name":"Alice"
    , "age": 30
    , "email": "alice@example.com"
    , "is_active": True
}

print(f"{user['name']} is {user['age']} years old.")

Alice is 30 years old.


In [ ]:
# 빈도수 계산
words = ["apple", "banana", "apple", "cherry", "banana", "date"]
frequency = {}

for word in words:
  frequency[word] = frequency.get(word, 0) + 1

print(frequency)

{'apple': 2, 'banana': 2, 'cherry': 1, 'date': 1}


In [ ]:
# 설정 관리
settings = {
    "theme":"dark"
    , "font_size": 14
    , "notifications": True
}

if settings["notifications"]:
  print(f"Notifications are enabled. Font size : {settings['font_size']}")

Notifications are enabled. Font size : 14


In [ ]:
# 제이슨 데이터 처리
import json

json_str = '{"name": "Bob", "age": 25, "city": "New York"}'
data = json.loads(json_str)

print(f"{data['name']} lives in {data['city']}")

Bob lives in New York


In [ ]:
# 명령어 매핑
def greet():
  print("Hello!")

def quit_program():
  print("Goodbye!")
  exit()

commands = {
    "hello": greet,
    "quit" : quit_program
}

while True:
  cmd = input("Enter a command: ").lower()
  if cmd in commands:
    commands[cmd]()
  else:
    print("Unknown command")

Enter a command: hell
Unknown command
Enter a command: hello
Hello!
Enter a command: greet
Unknown command
Enter a command: quit
Goodbye!
Enter a command: d
Unknown command


KeyboardInterrupt: Interrupted by user

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 샘플 데이터 생성
data = {
    'color': ['red', 'green', 'blue', 'green', 'red']
    , 'size' : ['S', 'M', 'L', 'M', 'S']
    , 'price' : [10, 20, 30, 20, 10]
    , 'label' : [0, 1, 0, 1, 0]
}

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# 데이터 로드
iris = load_iris()
x, y, = iris.data, iris.target

# 하이퍼파라미터 설정
param_grid = {
    'n_estimators':[10, 50, 100]
    ,'max_depth':[None, 10, 20, 30]
    , 'min_samples_split':[2, 5, 10]
}

In [ ]:
# 학생 성적 관리
student_data = {
    "Alice" : {
        "scores":[85, 90, 88]
        , "id": (123, "A")
    }
    , "Bob": {
        "scores":[78, 82, 79]
        , "id":(124, "B")
    }
    , "Charlie": {
        "scores": [92, 95, 91]
        , "id":(125, "C")
    }
}

# 학생 성적 추가
student_data["Alice"]["scores"].append(95)

# 특정 학생의 데이터 접근
print(student_data["Alice"]["scores"])

[85, 90, 88, 95]


## 집합(set)
- 중괄호 {}를 이용하여 정의, 순서가 정해지지 않고, 중복을 허용하지 않는 집합
- set() 함수는 리스트, 튜플, 딕셔너리를 셋으로 바꿈. 딕셔너리는 키(key)만 셋에 추가됨.
- 집합 연산자(& : 교집합, | : 합집합, - : 차집합) 사용 가능
- 저장한 순서대로 각 요소들이 저장되지 않으며, 중복을 허용 안함.
- True와 1은 같은 값으로 간주되며, False와 0도 같은 값으로 간주됨

In [1]:
fruits = {"apple", "orange", "banana", "apple", "pear"}
type(fruits)

set

In [2]:
fruits

{'apple', 'banana', 'orange', 'pear'}

### 집합 crud
- add()
  + 단일 요소를 집합에 추가할 때 사용
  + 기본 자료형과 튜플 추가함.
  + 리스트와 딕셔너리는 add()함수로 추가할 수 없음
  + 한 번에 하나의 요소만 추가 가능
  + 원본 집합을 직접 수정(반환값 없음.)
  ```
  my_set.add(element)
  ```
- update()
  + 기존 집합에 새로운 요소들을 추가할 때 사용
  + 리스트, 튜플, 딕셔너리, 문자를 추가함.
  + 딕셔너리는 키만 추가됨.
  + 여러 요소를 한번에 추가.
  + 중복된 요소는 자동으로 무시
  + 원본 집합을 직접 수정(반환값 없음.)
  ```
  existing_set.update(iterable)
  ```
- remove()
  + 특정 요소를 제거할 때 사용
  + 요소를 삭제함.
  + 함수의 인수는 셋에서 삭제할 값을 입력
  + 지정한 요소가 집합에 있으면 제거
  + 지정한 요소가 집합에 없으면 KeyError를 발생
  + 원본 집합을 직접 수정(반환값 없음.)
  ```
  my_set.remove(element)
  ```

In [3]:
fruits.add("apple")
fruits

{'apple', 'banana', 'orange', 'pear'}

In [4]:
fruits.add("mango")
fruits

{'apple', 'banana', 'mango', 'orange', 'pear'}

In [5]:
# update()
fruits = {'apple', 'banana', 'cherry'}
fruits.update(['orange', 'mango', 'apple'])
print(fruits)

{'cherry', 'apple', 'banana', 'orange', 'mango'}


In [6]:
# add()
fruits = {'apple', 'banana', 'cherry'}
fruits.add('orange')
print(fruits)

{'cherry', 'apple', 'banana', 'orange'}


In [7]:
# remove()
fruits = {'apple', 'banana', 'cherry'}
fruits.remove('banana')
print(fruits)

{'cherry', 'apple'}


In [8]:
# 중복 요소 제거
data = [1, 2, 2, 3, 4, 4, 5]

# 집합을 사용하여 중복 제거
unique_data = list(set(data))
print(unique_data)

[1, 2, 3, 4, 5]


In [9]:
# 교집합, 합집합, 차집합 연산
set_a = {1, 2, 3, 4}
set_b = {3, 4, 5, 6}

# 교집합
intersection = set_a & set_b
intersection

{3, 4}

In [10]:
# 합집합
union = set_a | set_b
union

{1, 2, 3, 4, 5, 6}

In [12]:
# 차집합
difference = set_a - set_b
difference

{1, 2}

In [13]:
# 원소의 존재 여부 확인
elements = {1, 2, 3, 4, 5}

print(3 in elements)

True


In [14]:
# 리스트의 고유 요소 추출
words = ["apple", "banana", "apple", "orange", "banana", "apple"]

unique_words = set(words)
unique_words

{'apple', 'banana', 'orange'}

In [15]:
# 여러 조건을 만족하는 데이터 필터링
set_a = {1, 2, 3, 4, 5}
set_b = {4, 5, 6, 7, 8}

# 두 집합에 모두 포함된 원소
common_elements = set_a & set_b
common_elements

{4, 5}

In [16]:
# 한 집합에만 포함된 원소
unique_elements = set_a ^ set_b
unique_elements

{1, 2, 3, 6, 7, 8}

In [17]:
# 훈련 및 테스트 테이터셋에서 고유값 비교
train_labels = ["cat", "dog", "bird"]
test_labels = ["dog", "fish", "cat"]

# 훈련 및 테스트 데이터의 고유값 추출
train_set = set(train_labels)
test_set = set(test_labels)

# 교집합을 사용하여 공통된 고유값 찾지
common_labels = train_set & test_set
common_labels

{'cat', 'dog'}

In [18]:
# 피처 엔지니어링에서 고유 단어 추출
documents = [
    "the cat in the hat"
    , "the quick brown fox"
    , "jumped over the lazy dog"
]

# 고유 단어 추출
unique_words = set()
for doc in documents:
  words = doc.split()
  unique_words.update(words)

unique_words

{'brown',
 'cat',
 'dog',
 'fox',
 'hat',
 'in',
 'jumped',
 'lazy',
 'over',
 'quick',
 'the'}

## mutable(가변) vs immutable(불변)
- 가변 자료구조(mutable)
  + 생성 후 내용을 변경할 수 있음
  + 메모리 주소가 변경되지 않음
  + ex) 리스트(list), 딕셔너리(dictionary), 집합(set)
- 분변 자료구조 (immutable)
  + 생성 후 내용을 변경할 수 없음
  + 내용 변경 시 새로운 객체가 생성
  + ex) 튜플(tuple), 문자열(str), 정수(int), 실수(float)

In [19]:
# 리스트(mutable)
list_a = [1, 2, 3]
list_b = list_a
list_b.append(4)
list_a

[1, 2, 3, 4]

In [20]:
# 튜플
tuple_a = (1, 2, 3)
tuple_b = tuple_a
tuple_b.append(4)

AttributeError: 'tuple' object has no attribute 'append'

In [21]:
tuple_b = tuple_b + (4, )
print(tuple_a)
print(tuple_b)

(1, 2, 3)
(1, 2, 3, 4)


In [22]:
# 얕은 복사와 깊은 복사에서 변경 가능
# 데이터 타입의 복사 방식에 따라 결과가 달라질 수 있다
import copy

# 얕은 복사 (shallow copy)
list_a = [[1, 2], [3, 4]]
list_b = list_a.copy()
list_b[0][0] = 9
print(list_a)
print(list_b)

[[9, 2], [3, 4]]
[[9, 2], [3, 4]]


In [23]:
# 깊은 복사 (deep copy)
list_c = [[1, 2], [3, 4]]
list_d = copy.deepcopy(list_c)
list_d[0][0] = 9
print(list_c)
print(list_d)

# copy()는 shallow copy 를 생성
# 즉, 새로운 객체를 만들지만 내부 객체에 대한 참조는 그대로 유지

# deepcopy()는 deep copy 를 생성
# 즉, 새로운 객체를 만들고 내부 객체도 모두 새로 생

[[1, 2], [3, 4]]
[[9, 2], [3, 4]]


## iterable (반복가능)
- 파이썬에서 순회할 수 있는 객체
- 요소를 하나씩 반환할 수 있는 객체
- for 루프에서 사용할 수 있음
- 리스트(list), 튜플(tuple), 문자열(str), 딕셔너리(dictionary), 집합(set), range 객체

In [24]:
# 리스트를 이용한 예시
my_list = [1, 2, 3, 4, 5]
for item in my_list:
  print(item, end='')
print()

12345


In [25]:
# 문자열을 이용한 예시
my_string = "Hello"
for char in my_string:
  print(char, end='')
print()

Hello


In [26]:
# range 객체를 이용한 예시
for num in range(5):
  print(num, end='')
print()

01234


In [27]:
# 딕셔너리를 이용한 예시
my_dict = {'a':1, 'b':2, 'c':3}
for key in my_dict:
  print(f"{key}:{my_dict[key]}", end='')
print()

a:1b:2c:3


In [28]:
# iterable 객체를 list()로 변환
print(list("Python"))

['P', 'y', 't', 'h', 'o', 'n']


In [29]:
# 사용자 정의 iterable 사용
for num in CountDown(5):
  print(num, end='')
print()

NameError: name 'CountDown' is not defined

## enumerate ()
- 반복 가능한 객체(iterable)를 인덱스와 함께 튜플 형태로 반환
- 반복문을 사용할 때 인덱스를 쉽게 접근 가능
- range() 함수를 이용해서 반복문의 인덱스를 만든 후 이를 이용해서 인덱스와 리스트 데이터를 처리하는 것은 직관적이지 못하고 코드가 어려워짐.
- 반복자(iterator) 또는 순서(sequence) 객체를 인수로 받음
- enumerate(iter)는 iter 객체를 (0, iter[0]), (1, iter[1]), (2, iter[2]), ... 형식으로 반환

In [30]:
fruits = ['watermelon', 'orange', 'mango', 'grape', 'banana', 'apple']
for fruit in fruits:
  print("데이터는 {}입니다.".format(fruit))

데이터는 watermelon입니다.
데이터는 orange입니다.
데이터는 mango입니다.
데이터는 grape입니다.
데이터는 banana입니다.
데이터는 apple입니다.


In [31]:
for i in range(len(fruits)):
  print("{}번째 데이터는 {}입니다.".format(i+1, fruits[i]))

1번째 데이터는 watermelon입니다.
2번째 데이터는 orange입니다.
3번째 데이터는 mango입니다.
4번째 데이터는 grape입니다.
5번째 데이터는 banana입니다.
6번째 데이터는 apple입니다.


In [32]:
fruits = ['watermelon', 'orange', 'mango', 'grape', 'banana', 'apple']
for index, value in enumerate(fruits):
  print("{}번째 데이터는 {}입니다.".format(index+1, value))

1번째 데이터는 watermelon입니다.
2번째 데이터는 orange입니다.
3번째 데이터는 mango입니다.
4번째 데이터는 grape입니다.
5번째 데이터는 banana입니다.
6번째 데이터는 apple입니다.


In [33]:
data = ['cat', 'dog', 'bird', 'fist']

for idx, value in enumerate(data):
  print(f"Index: {idx}, Value: {value}")

Index: 0, Value: cat
Index: 1, Value: dog
Index: 2, Value: bird
Index: 3, Value: fist


In [34]:
# 가상의 학습 손실 값
losses = [0.9, 0.7, 0.5, 0.3]

# enumerate()를 사용하여 에포크와 손실 값을 출력
for epoch, loss in enumerate(losses):
  print(f"Epoch: {epoch}, Loss: {loss}")

Epoch: 0, Loss: 0.9
Epoch: 1, Loss: 0.7
Epoch: 2, Loss: 0.5
Epoch: 3, Loss: 0.3


In [35]:
fruits = ['apple', 'banana', 'cherry']

for index, fruit in enumerate(fruits, start=1):
  print(f"Index: {index}, Fruit: {fruit}")

Index: 1, Fruit: apple
Index: 2, Fruit: banana
Index: 3, Fruit: cherry


In [37]:
# list comprehension 와 함께 사용
fruits = ['apple', 'banana', 'cherry']
indexed_fruits = [(index, fruit) for index, fruit in enumerate(fruits)]

indexed_fruits

[(0, 'apple'), (1, 'banana'), (2, 'cherry')]

In [38]:
# 딕셔너리로 변환
fruits = ['apple', 'banana', 'cherry']
fruit_dict = {index: fruit for index, fruit in enumerate(fruits)}
fruit_dict

{0: 'apple', 1: 'banana', 2: 'cherry'}

In [39]:
# 문자열에서 문자와 인덱스 출력
text = "hello"

for index, char in enumerate(text):
  print(f"Index: {index}, Character: {char}")

Index: 0, Character: h
Index: 1, Character: e
Index: 2, Character: l
Index: 3, Character: l
Index: 4, Character: o


In [42]:
# 문자열 형태의 특성을 숫자로 인코딩할 때 enumerate()를 사용하여 각 문자에 고유한 숫자 인덱스를 부여
from sklearn.preprocessing import LabelEncoder

labels = ['apple', 'banana', 'cherry']
encoder = LabelEncoder()
encoded_laberls = encoder.fit_transform(labels)

print(list(enumerate(encoder.classes_)))

[(0, 'apple'), (1, 'banana'), (2, 'cherry')]


In [45]:
# 모델 평가 시 enumerate()를 사용하여 각 샘플의 인덱스와 예측 결과를 매칭할 수 있음.
# 이를 통해 모델의 성능을 샘플 단위로 분석하거나, 오분류된 샘플을 확인 가능

from sklearn.metrics import accuracy_score

y_true = [0, 1, 0, 1, 0]
y_pred = [0, 0, 1, 2, 0]

for idx, (true, pred) in enumerate(zip(y_true, y_pred)):
  print(f"Sample {idx}: True={true}, Pred={pred}")

print(f"Overall accuracy: {accuracy_score(y_true, y_pred):.2f}")

Sample 0: True=0, Pred=0
Sample 1: True=1, Pred=0
Sample 2: True=0, Pred=1
Sample 3: True=1, Pred=2
Sample 4: True=0, Pred=0
Overall accuracy: 0.40
